apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: web
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 3000
    targetPort: web-port
    nodePort: 30002
  selector:
    app: web