# deployment版本
apiVersion: apps/v1
# 類型
kind: Deployment
# 識別資料（名字, labels）
metadata:
  name: my-deployment
  labels:
    app: web
# 設定內容
spec:
  # 幾個pod
  replicas: 1
  # 延遲，等待db啟用完成
  minReadySeconds: 12
  # 選擇適用labels（必須設定，方便以後新增labels需求）
  selector:
    matchLabels:
      app: web
  # 設定pod資訊
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      # 定義container
      - name: web-container
        image: todolist
        # 三種型態 Never: local無則err, Always: 每次啟動則更新, IfNotPresent: local無則pull 
        imagePullPolicy: Never
        ports:
        - name: web-port
          containerPort: 3000
        # 植入volume
        volumeMounts:
        - name: mysql-conf-volume
          mountPath: /etc/config
          readOnly: true
        # 就續探針
        readinessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 10
        # 存活探針
        livenessProbe:
          httpGet:
            path: /db_alive
            port: web-port
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        # 資源限制
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
          limits:
            memory: 200Mi
            cpu: 100m
      # 創建volumes
      volumes:
      - name: mysql-conf-volume
        # 設定檔
        configMap:
          name: mysql-conf