version: "3.8"

services:
  app:
    image: go_gin
    container_name: go_gin
    command: sh -c "cd hw_fifth_todolist && go run ."
    volumes:
      - ./go_gin:/go/src/hw_fifth_todolist
    ports:
      - 9012:3000
    networks:
      - test

networks:
  test:
    external: true
    name: database_test