# deployment版本
apiVersion: apps/v1
# 類型
kind: Deployment
# 識別資料（名字, labels）
metadata:
  name: web-deployment
  labels:
    app: web
    area: web
# 設定內容
spec:
  # 幾個pod
  replicas: 1
  # 延遲，等待db啟用完成
  # minReadySeconds: 12
  # 選擇適用labels（必須設定，方便以後新增labels需求）
  selector:
    matchLabels:
      app: web
      area: web
  # 設定pod資訊
  template:
    metadata:
      labels:
        app: web
        area: web
    spec:
      containers:
        # 定義container
        - name: web
          image: hw_ninth_web
          # 三種型態 Never: local無則err, Always: 每次啟動則更新, IfNotPresent: local無則pull
          imagePullPolicy: Never
          ports:
            - name: web-port
              containerPort: 30004
          # 植入volume
          volumeMounts:
            - name: configs
              mountPath: /app/configs/
              readOnly: true
              # 就續探針
          readinessProbe:
            httpGet:
              path: /alive
              port: 30004
            initialDelaySeconds: 15
          # 存活探針
          livenessProbe:
            httpGet:
              path: /alive
              port: 30004
            initialDelaySeconds: 20
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 3
          # 資源限制
          resources:
      # 創建volumes
      volumes:
        - name: configs
          # 設定檔
          configMap:
            name: configs
