apiVersion: v1
kind: Namespace
metadata:
  name: todolist
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quotas
  namespace: todolist
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "1"
    limits.memory: 2Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: object-quotas
  namespace: todolist
spec:
  hard:
    services: "10"
    secrets: "2"
    configmaps: "2"
    replicationcontrollers: "10"