apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-mysql-deployment
  labels:
    app: db-mysql
    area: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-mysql
      area: backend
  template:
    metadata:
      labels:
        app: db-mysql
        area: backend
    spec:
      containers:
        # db
        - name: my-db-container
          image: mysql:5.7
          # 環境
          env:
            # root密碼
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              # 從secret內拿資料
              secretKeyRef:
                name: mysql-secret
                key: db-root-password
            # 指定db
          - name: MYSQL_DATABASE
            value: test
          # mount volume
          volumeMounts:
          - mountPath: /var/lib/mysql
            name: mysql-volume
          # 資源限制
          resources:
      volumes:
      - name: mysql-volume
        persistentVolumeClaim:
          claimName: mysql-pvc