version: "3.8"

services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=testdb
    volumes:
      - ./mysql_volumes:/var/lib/mysql
    ports:
      - 9010:3306


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
    - mysql
    ports:
    - 9011:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306


  app:
      image: go_gin
      build:
        context: .
        dockerfile: ./docker/Dockerfile
      depends_on:
        - mysql
      volumes:
        - ./:/go/src/go_gin
      ports:
        - 9012:3000
