package api

import "github.com/gorilla/securecookie"

type SubjectRespond struct {
	ID      int    `json:"id"`
	Status  int    `json:"status"`
	Subject string `json:"subject"`
}

type NewSubjectRequest struct {
	Subject string `json:"subject" binding:"required,min=1"`
	User_id string `json:"user_id"`
}

type UpdateSubjectRequest struct {
	Id      string `json:"id" binding:"required,min=1"`
	Subject string `json:"subject" binding:"required,min=1"`
	Status  string `json:"status" binding:"required,min=1"`
}

type DeleteSubjectRequest struct {
	User_id string `json:"user_id"`
}

type LoginRequest struct {
	Username string `json:"username" binding:"required,alphanum,max=10,min=4"`
	Password string `json:"password" binding:"required,alphanum,max=10,min=4"`
}

type SessionData struct {
	// The ID of the session, generated by stores. It should not be used for
	// user data.
	ID     string
	Prefix string
	Codecs []securecookie.Codec
	// Values contains the user-data for the session.
	Datas  map[string]string
	Name   string
	MaxAge int
}
